### ISSUE TITLE
NotifyEarly = -1 not in effect when elevator is called on the same floor.

### ISSUE THREAD

**Issue by MultiMonorail** [eventhorizon5/skyscraper#15]
Regarding the new NotifyEarly parameter: When someone calls the elevator and both them and the elevator are on the same floor, the elevator will still chime even if NotifyEarly is set to -1.

**Comment by eventhorizon5** [comment]
That's something I'll look into, it happens because the NotifyEarly only affects arrival notifications (NotifyArrival() function), and if the elevator is on the same floor, that's not a standard arrival and so another handler (I think in the elevator door code) performs the chime.

**Comment by eventhorizon5** [comment]
This has been fixed.  Callbuttons now use the NotifyArrival() function along with a check for the NotifyEarly parameter.
