### ISSUE TITLE
NotifyEarly & NotifyLate Issues

### ISSUE THREAD

**Issue by MultiMonorail** [eventhorizon5/skyscraper#16]
1. When someone calls the elevator and both them and the elevator are on the same floor, the elevator will not chime nor light up the arrow when NotifyEarly is set to either 1 or 2.
2. When someone presses the down call button and both them and the elevator are on the same floor, the elevator will chime up if NotifyLate is true.

**Comment by eventhorizon5** [comment]
I'll look into those issues.  I did limited testing last night (mainly to quickly fix the normal behavior) but needed others to play around with the new features a lot to find the bugs.

**Comment by eventhorizon5** [comment]
These have both been fixed.
