### ISSUE TITLE
Floor Message Issue

### ISSUE THREAD

**Issue by MultiMonorail** [eventhorizon5/skyscraper#17]
When an elevator is called for the first time and the elevator is on the same floor as the person who called it, the floor message will notify that the elevator is on the floor assigned to 0.

Video for clarification (From Terrance V3):

https://user-images.githubusercontent.com/109993536/221048242-580a1ec6-fe9c-4055-81fe-7ce67ad82070.mp4

**Comment by eventhorizon5** [comment]
That's due to the fact that the elevator is now using the standard arrival notification instead of the old separate method.  I'll work on a fix for this.

**Comment by eventhorizon5** [comment]
This has been fixed.
