### ISSUE TITLE
Game Not saving resolution and resets

### ISSUE THREAD

**Issue by Danik2343** [eventhorizon5/skyscraper#19]
![image](https://user-images.githubusercontent.com/38865696/227731358-f255e44c-39c1-4aec-9f9d-36a365c7f338.png)

**Comment by eventhorizon5** [comment]
Do you have a scaling factor on your computer?  To see, go to Display Settings, then Scale and Layout.  If it's greater than 100%, you might have issues with that.  I'll be working on a fix for that.  If you set it to 100%, Skyscraper should work fine.

**Comment by Danik2343** [comment]
100 %.
Resolution 1360x768, i think problem in resolution.

**Comment by eventhorizon5** [comment]
That would be the problem, I set the resolution higher.  In the game, you can press F10 to full-screen it, and it should work fine then.  To change the resolution, open up the "C:\Program Files\Skyscraper\Skyscraper.ini" file with a text editor like notepad, and at the top you can set the resolution it uses, you should probably set it to 800x600.

**Comment by eventhorizon5** [comment]
You can also press Alt-F4 to exit if it's stuck, and the F5 key switches into freelook mode like most games.

**Comment by Danik2343** [comment]
Thanks for help!
