### ISSUE TITLE
[Linux] Skyscraper closes when returning to menu

### ISSUE THREAD

**Issue by cat1554** [eventhorizon5/skyscraper#2]
**What is the issue?**
- Skyscraper crashes when attempting to return to the menu.
- This is traced to an X Window System error with the error code of "BadWindow"

**How can this issue be reproduced?**
- Exit to the menu from a building. This issue may be Linux specific.

**What hardware and software are you using?**
- Ubuntu 22.04.1 LTS
- Latest version of the software as of Friday, 23 September, 2022 at 01:30 CDT

**Comment by eventhorizon5** [comment]
I noticed that this happens when trying to resize the window, in addition to the return to menu feature.  This might have to do with trying to run with legacy GTK2 code.  For more information, it crashes when doing a resize of the window when returning to the menu.

**Comment by eventhorizon5** [comment]
I've confirmed that this works fine when using GTK3, so the Skyscraper code is not at fault.

**Comment by eventhorizon5** [comment]
I found that the rendering issue is fixed in Ogre 1.13, so when I get the camera interface to work properly on that, then this issue will be fixed.

**Comment by eventhorizon5** [comment]
Closing since this is fixed in the new build.
