### ISSUE TITLE
[FR]: Catalog(1) + Local Network Mode (With ordinary character model) (2)

### ISSUE THREAD

**Issue by Danik2343** [eventhorizon5/skyscraper#20]
(1)
It will be possible to install large data packages in the manager.
New sounds, elevators, maps.
(2)
Local The local network will allow you to play with friends using standard character textures

**Comment by eventhorizon5** [comment]
Currently you can install many add-ons for Skyscraper, the website has some at https://custom.skyscrapersim.net which has new maps and elevators like you said.  The G1DP addon has lots and lots of addons.  Some of the maps use multiple sim engines to create larger maps with many buildings and elevators in each one.

For network play, I've wanted that for a very long time, and I'll try to eventually make it if it's possible.

**Comment by eventhorizon5** [comment]
Also check out the forum at https://skyscrapersimulatorforum.createaforum.com/

That forum also has more add-ons for Skyscraper and discussions.
