### ISSUE TITLE
Distination Dispatch Support for Elevators

### ISSUE THREAD

**Issue by Danik2343** [eventhorizon5/skyscraper#21]
Distination Dispatch Support for Elevators

**Comment by eventhorizon5** [comment]
This is a feature everybody seems to want.  It's currently in the planning stage, and a Git branch called "destination" has recently been created for the code work.

**Comment by eventhorizon5** [comment]
Basic destination dispatch support has been created and works (the controller only), it needs a lot of work though.

**Comment by eventhorizon5** [comment]
The new Destination Dispatch feature appears to be working well (at least with 1 elevator), the code has been merged into the master branch, and will be in the next build (development release).  Documentation still has to be made for it.

**Comment by eventhorizon5** [comment]
A development build with basic support of this feature has been released, see the website for downloads of it.
