### ISSUE TITLE
Directional Message Issue

### ISSUE THREAD

**Issue by MultiMonorail** [eventhorizon5/skyscraper#23]
This issue affects elevators that include the LevelingOpen Command with a value more than 0:
If an elevator has multiple calls from within the elevator going down, the elevator will still say that is going up.

**Comment by eventhorizon5** [comment]
I made a change which appears to have fixed this problem.  It was an issue in the GetArrivalDirection() elevator function where the up/down check would compare the same floor with both and chime up by default, I had it check the active queue direction instead if this situation pops up.  The code in that function is unnecessarily complicated so I'm hoping that it doesn't break more.
