### ISSUE TITLE
Idle Sound Issue

### ISSUE THREAD

**Issue by MultiMonorail** [eventhorizon5/skyscraper#24]
Custom elevator idle sounds are not functioning properly. The default sound is always playing, even if a custom sound is assigned in the building code.

**Comment by eventhorizon5** [comment]
Interesting, is this happening in both the Alpha 11 release and the current build, or just the current build?

**Comment by MultiMonorail** [comment]
It appears to be happening in just the current build.

**Comment by eventhorizon5** [comment]
CarIdleSound and MotorIdleSound parameters are working fine, is this for the old IdleSound parameter?  That one I think has issues, but it should also be broken in Alpha 11 if I'm seeing the code right.

**Comment by eventhorizon5** [comment]
Found it, it was the addition of the ID parameter, it didn't do the line check properly, I'll check things over to make sure there's no more script breakage.

**Comment by eventhorizon5** [comment]
This has been fixed in Git.

**Comment by eventhorizon5** [comment]
Since you said this is still not working, I'm testing it now and using the IdleSound command, and it works fine.  I'll check some other commands, but what building and idle sound command are you using that's breaking?

**Comment by MultiMonorail** [comment]
I meant the destination indicator sound, not the idle sound. The idle sound is working as it should.

**Comment by eventhorizon5** [comment]
Thanks for that, I'll see what's going on.
