### ISSUE TITLE
Reload Crash

### ISSUE THREAD

**Issue by MultiMonorail** [eventhorizon5/skyscraper#35]
When I try to reload the simulator (by either through the Engine Manager or by pressing Ctrl + R), the simulator instantly crashes. I can't seem to get the error message since the simulator closes out before I could copy it. I'm on a Windows 10 PC by the way.

**Comment by eventhorizon5** [comment]
It should be letting you see the stack backtrace at least.

Update - it happened to me, so I'll fix this issue.

**Comment by eventhorizon5** [comment]
This issue has been fixed, by using a pause function during the wxYield() call.
