### ISSUE TITLE
Newer versions of glibc

### ISSUE THREAD

**Issue by ppel54** [eventhorizon5/skyscraper#37]
When running the simulator on a Linux distribution which packages a newer version of glibc than 2.35 (in my case it's 2.37), the game won't run, with the output being:

`./bin/skyscraper: /home/user/Downloads/skyscraper/lib/libm.so.6: version GLIBC_2.35 not found (required by /usr/lib/libharfbuzz.so.0)`

What's strange is that this didn't use to happen a few versions ago.

**Comment by eventhorizon5** [comment]
I'll look into this.  The software was built on Debian 11, maybe including the glibc binary would fix it.

**Comment by eventhorizon5** [comment]
What Linux distro and version are you using?  I just tried the latest Ubuntu and it appears to be working on it.

**Comment by ppel54** [comment]
Arch Linux, which is a rolling release distro, but I think actually including it might be a good idea for now.

Edit: And the glibc version I have is 2.37.

**Comment by eventhorizon5** [comment]
Try running this test version of Skyscraper that I just put together, it includes the libharfbuzz and libpango libraries, let me know if it works for you:
https://www.skyscrapersim.net/downloads/dev/staging/skyscraper-test.tar.bz2

**Comment by ppel54** [comment]
Hmm... That did solve the glibc error, but now there's a different one.

`./bin/skyscraper: symbol lookup error: /usr/lib/libpangoft2-1.0.so.0: undefined symbol: pango_matrix_get_slant_ratio`

**Comment by eventhorizon5** [comment]
I found an Arch live cd distro, and got Skyscraper working on it.  It just needed a few extra libraries included with it (it didn't need glibc).  Download that staging file again (I re-uploaded it) and see if it works for you.

**Comment by ppel54** [comment]
Thank you so much, that worked perfectly.
