### ISSUE TITLE
The wrong elevator shows up when I press the button for a bank that has only certain serving floors past a certain point

### ISSUE THREAD

**Issue by aeroglass7** [eventhorizon5/skyscraper#47]
Step to reproduce:
1. Find an elevator bank that has some elevators that can't serve the bottom or top floor.
2. Go to the top or bottom floor one or more elevators serve before a specific elevator or specic elevator cars are the only ones that will go past that point.
3. When the elevators that can't go up or down further are waiting there or are close, press the down button if you are on the bottom floor or up if you are on the top floor of those elevators.

Those elevators will chime and show they can go down or up further than they actually can, resulting in you having to fight the system for the correct elevator.

**Comment by eventhorizon5** [comment]
Since I've been doing lots of bugfixes for an upcoming 2.0 stable release, I'll be working on this issue now.

**Comment by eventhorizon5** [comment]
This issue is now fixed.  It ended up being a bug in the elevator's AvailableForCall() function, which was not properly respecting elevator ranges.
