### ISSUE TITLE
Crash in buildings with AutomaticDoor2013

### ISSUE THREAD

**Issue by MultiMonorail** [eventhorizon5/skyscraper#66]
When I try to go through automatic doors made with AutomaticDoor2013 (Some of Mn10's buildings), I'm getting this crash report:

*** Unhandled Exception
   ExpCode: 0xC0000005
   ExpFlags: 0
   ExpAddress: 0xC4CE72CB

SymInit: Symbol SearchPath: '.', symOptions: 530, 

OS Version: 6.2.9200 ()

Loading symbols.......................................................................................................................

Call stack:
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\vector (1873): std::vector<SBS::DoorComponent *,std::allocator<SBS::DoorComponent *> >::size
C:\Users\multi\skyscraper\src\sbs\doorsystem.cpp (706): SBS::DoorWrapper::ResetFinished
C:\Users\multi\skyscraper\src\sbs\elevatordoor.cpp (634): SBS::ElevatorDoor::MoveDoors
C:\Users\multi\skyscraper\src\sbs\elevatordoor.cpp (408): SBS::ElevatorDoor::OpenDoors
C:\Users\multi\skyscraper\src\sbs\elevatorcar.cpp (1332): SBS::ElevatorCar::OpenDoors
C:\Users\multi\skyscraper\src\sbs\action.cpp (378): SBS::Action::Run
C:\Users\multi\skyscraper\src\sbs\action.cpp (99): SBS::Action::DoAction
C:\Users\multi\skyscraper\src\sbs\trigger.cpp (259): SBS::Trigger::DoAction
C:\Users\multi\skyscraper\src\sbs\trigger.cpp (317): SBS::Trigger::Loop
C:\Users\multi\skyscraper\src\sbs\object.cpp (585): SBS::Object::LoopChildren
C:\Users\multi\skyscraper\src\sbs\floor.cpp (964): SBS::Floor::Loop
C:\Users\multi\skyscraper\src\sbs\object.cpp (585): SBS::Object::LoopChildren
C:\Users\multi\skyscraper\src\sbs\manager.cpp (249): SBS::FloorManager::Loop
C:\Users\multi\skyscraper\src\sbs\object.cpp (585): SBS::Object::LoopChildren
C:\Users\multi\skyscraper\src\sbs\sbs.cpp (632): SBS::SBS::Loop
C:\Users\multi\skyscraper\src\vm\enginecontext.cpp (203): Skyscraper::EngineContext::Run
C:\Users\multi\skyscraper\src\vm\vm.cpp (290): Skyscraper::VM::RunEngines
C:\Users\multi\skyscraper\src\vm\vm.cpp (578): Skyscraper::VM::Run
C:\Users\multi\skyscraper\src\frontend\skyscraper.cpp (424): Skyscraper::Skyscraper::Loop
C:\Users\multi\skyscraper\src\frontend\mainscreen.cpp (216): Skyscraper::MainScreen::OnIdle
00007FFAC6363884 (wxbase32u_vc_custom): (filename not available): wxAppConsoleBase::CallEventHandler
00007FFAC64671AF (wxbase32u_vc_custom): (filename not available): wxEvtHandler::ProcessEventIfMatchesId
00007FFAC6466D7C (wxbase32u_vc_custom): (filename not available): wxEventHashTable::HandleEvent
00007FFAC646804D (wxbase32u_vc_custom): (filename not available): wxEvtHandler::TryHereOnly
00007FFAC6467113 (wxbase32u_vc_custom): (filename not available): wxEvtHandler::ProcessEvent
00007FFAC6467C2A (wxbase32u_vc_custom): (filename not available): wxEvtHandler::SafelyProcessEvent
00007FFAC5600307 (wxmsw32u_core_vc_custom): (filename not available): wxWindowBase::SendIdleEvents
00007FFAC550E06A (wxmsw32u_core_vc_custom): (filename not available): wxAppBase::ProcessIdle
00007FFAC63999C9 (wxbase32u_vc_custom): (filename not available): wxEventLoopBase::ProcessIdle
00007FFAC6399795 (wxbase32u_vc_custom): (filename not available): wxEventLoopManual::DoRun
00007FFAC6399A4A (wxbase32u_vc_custom): (filename not available): wxEventLoopBase::Run
00007FFAC63661B7 (wxbase32u_vc_custom): (filename not available): wxAppConsoleBase::MainLoop
00007FFAC63E9F1C (wxbase32u_vc_custom): (filename not available): wxEntryReal
00007FFAC64C6458 (wxbase32u_vc_custom): (filename not available): wxEntry
C:\Users\multi\skyscraper\src\frontend\skyscraper.cpp (135): main
D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl (288): __scrt_common_main_seh
00007FFB850E7374 (KERNEL32): (filename not available): BaseThreadInitThunk
00007FFB85A9CC91 (ntdll): (filename not available): RtlUserThreadStart

Simulator State Dump
--------------------------
Platform: Windows x86 64-bit
Renderer: OpenGL
Frontend version: 2.1.0.3556
SBS version: 1.1.0.3556
Instance number: 0
Building Name: Serenity Hospital - Narita Building
Building Filename: Serenity Hospital - Narita Building.bld
Building Version: 
InStairwell: false
InElevator: false
InShaft: false
CameraFloor: 0
ElevatorNumber: 1
CarNumber: 1
ElevatorSync: false
Running Time: 3.75
BuildingsEnabled: true
ExternalEnabled: true
LandscapeEnabled: true
SkyboxEnabled: true
Verbose: false
InterfloorOnTop: false
Object Count: 26916
Camera Floor: 0
Camera Position: 12.09, 5.00, 2.96

**Comment by eventhorizon5** [comment]
I went over the code and fixed every usage of the door array for this, let me know if it's working for you now.

**Comment by MultiMonorail** [comment]
I tried the new commits, and I'm now getting this error:

*** Unhandled Exception
   ExpCode: 0xC0000005
   ExpFlags: 0
   ExpAddress: 0xB9EA72CB

SymInit: Symbol SearchPath: '.', symOptions: 530, 

OS Version: 6.2.9200 ()

Loading symbols.......................................................................................................................

Call stack:
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\vector (1873): std::vector<SBS::DoorComponent *,std::allocator<SBS::DoorComponent *> >::size
C:\Users\multi\skyscraper\src\sbs\doorsystem.cpp (730): SBS::DoorWrapper::ResetFinished
C:\Users\multi\skyscraper\src\sbs\elevatordoor.cpp (634): SBS::ElevatorDoor::MoveDoors
C:\Users\multi\skyscraper\src\sbs\elevatordoor.cpp (408): SBS::ElevatorDoor::OpenDoors
C:\Users\multi\skyscraper\src\sbs\elevatorcar.cpp (1332): SBS::ElevatorCar::OpenDoors
C:\Users\multi\skyscraper\src\sbs\action.cpp (378): SBS::Action::Run
C:\Users\multi\skyscraper\src\sbs\action.cpp (99): SBS::Action::DoAction
C:\Users\multi\skyscraper\src\sbs\trigger.cpp (259): SBS::Trigger::DoAction
C:\Users\multi\skyscraper\src\sbs\trigger.cpp (317): SBS::Trigger::Loop
C:\Users\multi\skyscraper\src\sbs\object.cpp (585): SBS::Object::LoopChildren
C:\Users\multi\skyscraper\src\sbs\floor.cpp (964): SBS::Floor::Loop
C:\Users\multi\skyscraper\src\sbs\object.cpp (585): SBS::Object::LoopChildren
C:\Users\multi\skyscraper\src\sbs\manager.cpp (249): SBS::FloorManager::Loop
C:\Users\multi\skyscraper\src\sbs\object.cpp (585): SBS::Object::LoopChildren
C:\Users\multi\skyscraper\src\sbs\sbs.cpp (632): SBS::SBS::Loop
C:\Users\multi\skyscraper\src\vm\enginecontext.cpp (203): Skyscraper::EngineContext::Run
C:\Users\multi\skyscraper\src\vm\vm.cpp (290): Skyscraper::VM::RunEngines
C:\Users\multi\skyscraper\src\vm\vm.cpp (578): Skyscraper::VM::Run
C:\Users\multi\skyscraper\src\frontend\skyscraper.cpp (424): Skyscraper::Skyscraper::Loop
C:\Users\multi\skyscraper\src\frontend\mainscreen.cpp (216): Skyscraper::MainScreen::OnIdle
00007FFAB90B3884 (wxbase32u_vc_custom): (filename not available): wxAppConsoleBase::CallEventHandler
00007FFAB91B71AF (wxbase32u_vc_custom): (filename not available): wxEvtHandler::ProcessEventIfMatchesId
00007FFAB91B6D7C (wxbase32u_vc_custom): (filename not available): wxEventHashTable::HandleEvent
00007FFAB91B804D (wxbase32u_vc_custom): (filename not available): wxEvtHandler::TryHereOnly
00007FFAB91B7113 (wxbase32u_vc_custom): (filename not available): wxEvtHandler::ProcessEvent
00007FFAB91B7C2A (wxbase32u_vc_custom): (filename not available): wxEvtHandler::SafelyProcessEvent
00007FFAB9520307 (wxmsw32u_core_vc_custom): (filename not available): wxWindowBase::SendIdleEvents
00007FFAB942E06A (wxmsw32u_core_vc_custom): (filename not available): wxAppBase::ProcessIdle
00007FFAB90E99C9 (wxbase32u_vc_custom): (filename not available): wxEventLoopBase::ProcessIdle
00007FFAB90E9795 (wxbase32u_vc_custom): (filename not available): wxEventLoopManual::DoRun
00007FFAB90E9A4A (wxbase32u_vc_custom): (filename not available): wxEventLoopBase::Run
00007FFAB90B61B7 (wxbase32u_vc_custom): (filename not available): wxAppConsoleBase::MainLoop
00007FFAB9139F1C (wxbase32u_vc_custom): (filename not available): wxEntryReal
00007FFAB9216458 (wxbase32u_vc_custom): (filename not available): wxEntry
C:\Users\multi\skyscraper\src\frontend\skyscraper.cpp (135): main
D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl (288): __scrt_common_main_seh
00007FFB850E7374 (KERNEL32): (filename not available): BaseThreadInitThunk
00007FFB85A9CC91 (ntdll): (filename not available): RtlUserThreadStart

Simulator State Dump
--------------------------
Platform: Windows x86 64-bit
Renderer: OpenGL
Frontend version: 2.1.0.3556
SBS version: 1.1.0.3556
Instance number: 0
Building Name: Serenity Hospital - Narita Building
Building Filename: Serenity Hospital - Narita Building.bld
Building Version: 
InStairwell: false
InElevator: false
InShaft: false
CameraFloor: 0
ElevatorNumber: 1
CarNumber: 1
ElevatorSync: false
Running Time: 37.20
BuildingsEnabled: true
ExternalEnabled: true
LandscapeEnabled: true
SkyboxEnabled: true
Verbose: false
InterfloorOnTop: false
Object Count: 26916
Camera Floor: 0
Camera Position: -13.90, 5.00, -6.22

**Comment by eventhorizon5** [comment]
Looks like that's the same crash, I'll do some tests later to see what it's doing.

**Comment by eventhorizon5** [comment]
I recently made a commit that should fix the remaining issues, see if it works for you now.  I went over the code quite a bit, and didn't notice anything else that could cause issues so far.

**Comment by MultiMonorail** [comment]
I tested the newest commit, and the doors work now!
